name: Build and Deploy
on:
  push:
    branches:
      - main # If your default branch is named something else, change this

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libudev-dev pkg-config libx11-dev libxi-dev libgl1-mesa-dev gcc

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Build
        env:
          RUSTFLAGS: >-
            -C link-arg=--export=main
            -C link-arg=--export=malloc
            -C link-arg=--export=free
            -C link-arg=--export=allocate_vec_u8
            -C link-arg=--export=frame
            -C link-arg=--export=key_down
            -C link-arg=--export=key_up
            -C link-arg=--export=mouse_move
            -C link-arg=--export=mouse_down
            -C link-arg=--export=mouse_up
            -C link-arg=--export=resize
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Prepare Deployment Directory
        run: |
          mkdir -p ./deploy/assets
          cp ./target/wasm32-unknown-unknown/release/my-game.wasm ./deploy/
          cp index.html ./deploy/
          cp -r assets/ ./deploy/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
